default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV["PASS_POSTGRESQL"] %>
  host: localhost

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_project_development

test:
  <<: *default
  database: blog_app_project_test

production:
  <<: *default
  database: blog_app_project_production
  # username: blog_app_project
  # password: <%= ENV['BLOG_APP_PROJECT_DATABASE_PASSWORD'] %>
